defaults: &defaults
  email:
    notifications_sender: 'jmateovidalb@gmail.com'
    devise_sender: 'jmateovidalb@gmail.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults